services:
    payment.perfectmoney.client:
        class: vSymfo\Payment\PerfectMoneyBundle\Client\SciClient
        arguments: [%vsymfo_payment_perfectmoney.pm_member_id%, %vsymfo_payment_perfectmoney.pm_password%, %vsymfo_payment_perfectmoney.alternate_phrase_hash%, %vsymfo_payment_perfectmoney.payee_account%]

    payment.plugin.perfectmoney:
        class: vSymfo\Payment\PerfectMoneyBundle\Plugin\PerfectMoneyPlugin
        arguments: [@router, @payment.perfectmoney.client, @payment.event_dispatcher]
        tags: [{name: payment.plugin}]

    payment.form.perfectmoney_type:
        class: vSymfo\Payment\PerfectMoneyBundle\Form\PerfectMoneyType
        tags:
            - {name: payment.method_form_type}
            - {name: form.type, alias: perfect_money_sci_payment}
